# Generated by Django 6.0.7 on 2026-08-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='budget_range',
        ),
    ]
